apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "8181"
    port: 8181
    targetPort: 8080
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
