# Example configuration
---
activityDelay: 1
phantom:
  baseUrl: http://172.17.0.2:8080/jpetstore/
  path: /home/reiner/Projects/iObserve/experiments/tools/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  timeout: 1000
workloads:
  - name: AccountManager
    intensity:
      type: org.iobserve.selenium.configuration.ConstantWorkloadIntensity
      name: AccountManager
      spawnPerSecond: 0.1
      durations: [ 100, 50 ]
      delays: [ 50, 50 ]
  - name: BrowsingUser
    intensity:
      type: org.iobserve.selenium.configuration.ConstantWorkloadIntensity
      name: BrowsingUser
      spawnPerSecond: 0.2
      durations: [ 200 ]
behaviors:
  AccountManager:
    name: AccountManager
    activityDelay: 2
    subbehaviors:
      - name: LoginJPetStoreTask
        parameters:
          username: "j2ee"
          password: "j2ee"
      - name: ChangeAccountInformationTask
        repetition: { min: 1, max: 10 }
        parameters:
          attribute: ADDRESS2
          value: "Christian-Albrechts-Platz 4"
      - name: ViewOrderTask
        repetition: { min: 1, max: 20 }
  BrowsingUser:
    name: BrowsingUser
    activityDelay: 2
    subbehaviors:
      - name: ViewProductTask
        repetition: { min: 1, max: 5 }
        parameters:
          category: CATS
      - name: ViewProductTask
        repetition: { min: 1, max: 6 }
        parameters:
          category: FISH
  BuyCartBehavior:
    name: BuyCartBehavior
    subbehaviors:
      - name: LoginJPetStoreTask
        parameters:
          username: j2ee
          password: j2ee
      - name: CheckoutJPetStoreTask
  CatLoverBehavior:
    name: CatLoverBehavior
    subbehaviors:
      - name: AddCatsToCartTask
        repetition: { min: 1, max: 10 }
        parameters:
          amountOfCat: 9
          catPosition: 0
      - name: LoginJPetStoreTask
        parameters:
          username: j2ee
          password: j2ee
      - name: CheckoutJPetStoreTask
  CatToCartBehavior:
    name: CatToCartBehavior
    subbehaviors:
      - name: AddCatsToCartTask
        repetition: { min: 1, max: 10 }
        parameters:
          amountOfCat: 9
          catPosition: 0
  FishLoverBehavior:
    name: FishLoverBehavior
    subbehaviors:
      - name: AddFishToCartTask
        repetition: { min: 1, max: 10 }
        parameters:
          amountOfCat: 9
          fishPosition: 0
      - name: LoginJPetStoreTask
        parameters:
          username: j2ee
          password: j2ee
      - name: CheckoutJPetStoreTask
  NewCustomerBehavior:
    name: NewCustomerBehavior
    subbehaviors:
      - name: CreateNewCustomerTask
        parameters:
          username: Newone
          password: new
      - name: AddReptilesToCartTask
        repetition: { min: 1, max: 1 }
        parameters:
          amount: 1
          itemPosition: 1
      - name: LoginJPetStoreTask
        parameters:
          username: Newone
          password: new
      - name: CheckoutJPetStoreTask
  SingleCatBuyerBehavior:
    name: SingleCatBuyerBehavior
    subbehaviors:
      - name: AddCatsToCartTask
        repetition: { min: 1, max: 1 }
        parameters:
          amount: 1
          itemPosition: 1
      - name: LoginJPetStoreTask
        parameters:
          username: j2ee
          password: j2ee
      - name: CheckoutJPetStoreTask
  SingleCatBuyerWorkload:
    name: SingleReptileBuyerBehavior
    subbehaviors:
      - name: AddReptilesToCartTask
        repetition: { min: 1, max: 1 }
        parameters:
          amount: 1
          itemPosition: 1
      - name: LoginJPetStoreTask
        parameters:
          username: j2ee
          password: j2ee
      - name: CheckoutJPetStoreTask

