apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: order
  name: order
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: order
    spec:
      containers:
      - image: blade1.se.internal:5000/jpetstore-order-service
        name: order
        resources: {}
        env:
        - name: LOGGER
          value: %LOGGER%
      restartPolicy: Always
status: {}
