apiVersion: v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: order
    spec:
      containers:
      - image: blade1.se.internal:5000/jpetstore-order-service
        name: order
        resources: {}
        env:
        - name: LOGGER
          value: %LOGGER%
      restartPolicy: Always
status: {}
